# Generated by Django 5.2.13 on 2026-04-27 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_generated_url_alter_image_file'),
        ('jobs', '0003_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='best_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_jobs', to='images.image'),
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default='kodeviolimited@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
