# Generated by Django 5.2.13 on 2026-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_alter_image_options_image_created_at_image_order_and_more"),
        ("jobs", "0006_analytics_alter_job_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Analytics",
        ),
        migrations.RemoveField(
            model_name="job",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="job",
            name="stripe_payment_id",
        ),
        migrations.AddField(
            model_name="job",
            name="ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("READY", "Ready"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="jobs_job_status_7d017a_idx"),
        ),
    ]
