# Generated by Django 5.2.13 on 2026-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_image_file_alter_image_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
