# Generated by Django 5.2.13 on 2026-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="generated_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="jobs/"),
        ),
    ]
