# Generated by Django 5.2.13 on 2026-04-29 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_alter_image_id"),
        ("jobs", "0006_analytics_alter_job_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="image",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["job", "type"], name="images_imag_job_id_7996be_idx"
            ),
        ),
    ]
