# Generated by Django 5.2.13 on 2026-04-29 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_delete_analytics_remove_job_payment_status_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeevent",
            name="event_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="stripe", max_length=50)),
                ("provider_payment_id", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.payment",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["job", "status"], name="payments_pa_job_id_dde10c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("provider", "provider_payment_id")},
        ),
    ]
